portfolio/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('user_login/', views.user_login, name='user_login'),
    path('user_logout/', views.user_logout, name='user_logout'),
    path('combined_list/', views.combined_list, name='combined_list'),

    path('add_blog/', views.add_blog, name='add_blog'),
    path('blogs/', views.blog_list, name='blog_list'),
    path('blogs/<slug:slug>/', views.blog_detail, name='blog_detail'),
    path('blogs/<slug:slug>/edit/', views.update_blog, name='update_blog'),
    path('blogs/<slug:slug>/delete/', views.delete_blog, name='delete_blog'),

    path('projects/', views.project_list, name='project_list'),
    path('projects/<int:pk>/', views.project_detail, name='project_detail'),
    path('projects/new/', views.add_project, name='add_project'),
    path('projects/<int:pk>/edit/', views.update_project, name='update_project'),
    path('projects/<int:pk>/delete/', views.delete_project, name='delete_project'),

    path('photos/', views.photo_list, name='photo_list'),
    path('photos/<int:pk>/', views.photo_detail, name='photo_detail'),
    path('photos/new/', views.add_photo, name='add_photo'),
    path('photos/<int:pk>/edit/', views.update_photo, name='update_photo'),
    path('photos/<int:pk>/delete/', views.delete_photo, name='delete_photo'),
]

webportfolio/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portfolio.urls')),
]

portfolio/models.py
from django.db import models
from django.contrib.auth.models import User

class Blog(models.Model):
    slug = models.SlugField(unique=True, max_length=200)
    title = models.CharField(max_length=200)
    content = models.TextField()
    image_url = models.URLField(max_length=200, blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    date_published = models.DateField(auto_now_add=True)
    post_count = models.IntegerField(default=0)

    def __str__(self):
        return f'{self.title} - {self.date_published}'

    class Meta:
        ordering = ['-date_published']  


class Project(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    project_link = models.URLField(max_length=200, blank=True)

    def __str__(self):
        return self.title


class Photo(models.Model):
    image_url = models.URLField(max_length=200)
    caption = models.TextField(blank=True)

    def __str__(self):
        return self.image_url

portfolio/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.forms.widgets import PasswordInput, TextInput
from django import forms
from .models import Blog, Project, Photo



class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=TextInput())
    password = forms.CharField(widget=PasswordInput())


class BlogForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ['slug', 'title', 'content', 'image_url', 'author', 'post_count']

class UpdateBlogForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ['slug', 'title', 'content', 'image_url', 'author', 'post_count']

class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ['title', 'description', 'project_link']

class UpdateProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ['title', 'description', 'project_link']

class PhotoForm(forms.ModelForm):
    class Meta:
        model = Photo
        fields = ['image_url', 'caption']

class UpdatePhotoForm(forms.ModelForm):
    class Meta:
        model = Photo
        fields = ['image_url', 'caption']


class DeleteForm(forms.Form):
    confirm = forms.BooleanField(label='Confirm deletion', required=True)

portfolio/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from .forms import BlogForm, ProjectForm, PhotoForm
from .models import Blog, Project, Photo

def home(request):
    blogs = Blog.objects.all()
    projects = Project.objects.all()
    photos = Photo.objects.all()
    context = {
        'blogs': blogs,
        'projects': projects,
        'photos': photos
    }
    return render(request, 'portfolio/home.html')

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('combined_list')
        else:
            return render(request, 'portfolio/user_login.html', {'error': 'Invalid credentials'})
    return render(request, 'portfolio/user_login.html')

def user_logout(request):
    logout(request)
    return redirect('home')


#admin
@login_required(login_url='user_login')
def combined_list(request):
    blogs = Blog.objects.all()
    projects = Project.objects.all()
    photos = Photo.objects.all()
    context = {
        'blogs': blogs,
        'projects': projects,
        'photos': photos
    }
    return render(request, 'portfolio/combined_list.html', context)


#blog
def blog_list(request):
    blogs = Blog.objects.all()
    return render(request, 'portfolio/blog_list.html', {'blogs': blogs})

def blog_detail(request, slug):
    blog = get_object_or_404(Blog, slug=slug)
    return render(request, 'portfolio/blog_detail.html', {'blog': blog})


@login_required(login_url='user_login')
def add_blog(request):
    if request.method == 'POST':
        form = BlogForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('blog_list')
        else:
            print(form.errors)  # Debugprintformerrors
    else:
        form = BlogForm()
    return render(request, 'portfolio/add_blog.html', {'form': form})


@login_required(login_url='user_login')
def update_blog(request, slug):
    blog = get_object_or_404(Blog, slug=slug)
    form = BlogForm(request.POST or None, instance=blog)
    if form.is_valid():
        form.save()
        return redirect('blog_list')
    return render(request, 'portfolio/blog_update.html', {'form': form})

@login_required(login_url='user_login')
def delete_blog(request, slug):
    blog = get_object_or_404(Blog, slug=slug)
    if request.method == 'POST':
        blog.delete()
        return redirect('blog_list')
    return render(request, 'portfolio/blog_delete.html', {'blog': blog})


#project
def project_list(request):
    projects = Project.objects.all()
    return render(request, 'portfolio/project_list.html', {'projects': projects})

def project_detail(request, pk):
    project = get_object_or_404(Project, pk=pk)
    return render(request, 'portfolio/project_detail.html', {'project': project})

@login_required(login_url='user_login')
def add_project(request):
    if request.method == 'POST':
        form = ProjectForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('project_list')
    else:
        form = ProjectForm()
    return render(request, 'portfolio/add_project.html', {'form': form})

@login_required(login_url='user_login')
def update_project(request, pk):
    project = get_object_or_404(Project, pk=pk)
    if request.method == 'POST':
        form = ProjectForm(request.POST, request.FILES, instance=project)
        if form.is_valid():
            form.save()
            return redirect('project_list')
    else:
        form = ProjectForm(instance=project)
    return render(request, 'portfolio/project_update.html', {'form': form})

@login_required(login_url='user_login')
def delete_project(request, pk):
    project = get_object_or_404(Project, pk=pk)
    if request.method == 'POST':
        project.delete()
        return redirect('project_list')
    return render(request, 'portfolio/project_delete.html', {'project': project})


#photo
def photo_list(request):
    photos = Photo.objects.all()
    return render(request, 'portfolio/photo_list.html', {'photos': photos})

def photo_detail(request, pk):
    photo = get_object_or_404(Photo, pk=pk)
    return render(request, 'portfolio/photo_detail.html', {'photo': photo})

@login_required(login_url='user_login')
def add_photo(request):
    if request.method == 'POST':
        form = PhotoForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('photo_list')
    else:
        form = PhotoForm()
    return render(request, 'portfolio/add_photo.html', {'form': form})

@login_required(login_url='user_login')
def update_photo(request, pk):
    photo = get_object_or_404(Photo, pk=pk)
    if request.method == 'POST':
        form = PhotoForm(request.POST, request.FILES, instance=photo)
        if form.is_valid():
            form.save()
            return redirect('photo_list')
    else:
        form = PhotoForm(instance=photo)
    return render(request, 'portfolio/photo_update.html', {'form': form})

@login_required(login_url='user_login')
def delete_photo(request, pk):
    photo = get_object_or_404(Photo, pk=pk)
    if request.method == 'POST':
        photo.delete()
        return redirect('photo_list')
    return render(request, 'portfolio/photo_delete.html', {'photo': photo})

portfolio/templates/portfolio/add_blog.html
{% extends 'portfolio/base.html' %}

{% block content %}
  <div class="container" style="background-color: #f8f8f8; padding: 20px;">
    <div class="row justify-content-center">
      <div class="col-md-8">
        <h1 class="text-center text-info">Add Blog</h1><br>
        <form method="post" enctype="multipart/form-data">
          {% csrf_token %}
          
          <div class="form-group">
            <label for="{{blog.slug}}">Slug:</label>
            <input type="text" name="slug"  maxlength="200" required id="id_slug" class="form-control">
          </div>
        
          <div class="form-group">
            <label for="{{blog.title}}">Title:</label>
            <input type="text" name="title" maxlength="200" required id="id_title" class="form-control">
          </div>
        
          <div class="form-group">
            <label for="{{blog.content}}">Content:</label>
            <textarea name="content" cols="30" rows="10" required id="id_content" class="form-control"></textarea>
          </div>
        
          <div class="form-group">
            <label for="{{blog.image_url}}">Image URL:</label>
            <input type="url" name="image_url" maxlength="200" id="id_image_url" class="form-control">
          </div>
         
          <div class="form-group">
            <label for="{{blog.author}}">Author:</label>
            <select name="author" required id="id_author" class="form-control">
              <option value="">---------</option>
              <option value="1" selected>red</option> 
            </select>
          </div>

          <div class="form-group">
            <label for="id_post_count">Post count:</label>
            <input type="number" name="post_count" value="0" required id="id_post_count">
          </div>

          <div class="d-flex justify-content-end mt-3">
            <button type="submit" class="btn btn-primary mr-2">Save</button>
            <a href="{% url 'blog_list' %}" class="btn btn-secondary">Cancel</a>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

portfolio/templates/portfolio/add_photo.html
{% extends 'portfolio/base.html' %}

{% block content %}



<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="card">
        <div class="card-body">
          <h1 class="text-center mb-4">Add Photos</h1>
          <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group">
              <label for="id_caption">Caption:</label>
              <input type="text" name="caption" id="id_caption" class="form-control" value="{{ form.caption.value|default_if_none:'' }}">
            </div>
            
            <div class="form-group">
              <label for="id_image_url">Image URL:</label>
              {{ form.image_url.errors }}
              <input type="url" name="image_url" id="id_image_url" class="form-control" value="{{ form.image_url.value|default_if_none:'' }}">
            </div>
            <button type="submit" class="btn btn-primary btn-block">Save</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div><br><br>
{% endblock %}

portfolio/templates/portfolio/add_project.html
{% extends 'portfolio/base.html' %}

{% block content %}



<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="card">
        <div class="card-body">
          <h1 class="text-center mb-4">Add Projects</h1>
          <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group">
              <label for="id_title">Title:</label>
              <input type="text" name="title" id="id_title" class="form-control">
            </div>
            <div class="form-group">
              <label for="id_image">Description:</label>
              <input type="text" name="description" id="id_description" class="form-control">
            </div>
            <div class="form-group">
              <label for="id_image_url">Project Link:</label>
              <input type="url" name="project_link" id="id_project_link" class="form-control">
            </div>
            <button type="submit" class="btn btn-primary btn-block">Save</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div><br><br>
{% endblock %}

portfolio/templates/portfolio/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <script src="{% static 'js/app.js' %}"></script>
    <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}">
    <link href="https://fonts.googleapis.com/css2?family=Varela+Round&display=swap" rel="stylesheet">
    <title>Blog by Ro</title>
</head>
<body>

    <nav class="navbar navbar-expand-lg navbar-light" style="background-color: rgb(92, 227, 77);" >
        <a class="navbar-brand" href="/user_login">Roc World</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="/">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/blogs">Blog</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/projects">Projects</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/photos">Photos</a>
                </li>
                
            </ul>
        </div>
    </nav>

    <div class="content-wrapper" style="background-color: rgb(37, 42, 37); padding: 20px;">
        {% block content %}
    
        {% endblock %}
    </div>

    

    <footer class="footer mt-auto py-3 bg-light" style="text-align: center; background: linear-gradient(to top, pink, rgb(36, 205, 27));">

        <div class="row mt-5">
            <div class="col-md-8 offset-md-2 text-center">
                <blockquote class="blockquote">
                    <p class="mb-0 text-dark">"Your limitation—it's only your imagination."</p>
                    <footer class="blockquote-footer">Unknown</footer>
                </blockquote>
            </div>
            
        </div>
        
        <div class="container">
            <span class="text-muted"><a href="https://wa.me/qr/RMTIILK3PEM3O1">Click here for comments, contact, etc...</a></span>
            <p class="text-center"><a class="navbar-brand" href="/combined_list">&copy;Roc2024</a></p>
        </div>
    </footer>



    <!-- Bootstrap JS Bundle with Popper -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>


</body>
</html>

portfolio/templates/portfolio/blog_delete.html
{% extends 'portfolio/base.html' %}

{% block content %}
<div class="container" style="background-color: #343a40; padding: 20px; border-radius: 8px;">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="text-center text-white">
        <h1>Confirm Delete</h1>
        <p>Are you sure you want to delete the blog post "{{ blog.title }}"?</p>
        <form method="post">
          {% csrf_token %}
          <div class="d-flex justify-content-center mt-3">
            <button type="submit" class="btn btn-danger mr-3">Yes, delete</button>
            <a href="{% url 'blog_detail' blog.slug %}" class="btn btn-secondary">Cancel</a>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

portfolio/templates/portfolio/blog_list.html
{% extends 'portfolio/base.html' %}

{% block content %}

  <div class="container mt-5 text-center">
      <div class="jumbotron">
          <h1>Latest Blog Posts</h1><br><br><hr>
          <div class="container text-center">
              <div class="row">
                  {% for blog in blogs %}
                  <div class="col-md-4 mb-4">
                      <a href="{% url 'blog_detail' blog.slug %}">{{blog.title}}</a><hr>  
                  </div>
                  {% endfor %}
              </div>
          </div>
      </div>
  </div>
  <hr>
{% endblock %}

portfolio/templates/portfolio/blog_update.html
{% extends 'portfolio/base.html' %}

{% block content %}
  <div class="container" style="background-color: #f8f8f8; padding: 20px;">
    <div class="row justify-content-center">
      <div class="col-md-8">
        <h1 class="text-center text-info">Update Blog</h1><br>
        <form method="post" enctype="multipart/form-data">
          {% csrf_token %}
          
          <div class="form-group">
            <label for="{{blog.slug}}">Slug:</label>
            <input type="text" name="slug"  maxlength="200" required id="id_slug" class="form-control">
          </div>
        
          <div class="form-group">
            <label for="{{blog.title}}">Title:</label>
            <input type="text" name="title" maxlength="200" required id="id_title" class="form-control">
          </div>
        
          <div class="form-group">
            <label for="{{blog.content}}">Content:</label>
            <textarea name="content" cols="30" rows="10" required id="id_content" class="form-control"></textarea>
          </div>
        
          <div class="form-group">
            <label for="{{blog.image_url}}">Image URL:</label>
            <input type="url" name="image_url" maxlength="200" id="id_image_url" class="form-control">
          </div>
         
          <div class="form-group">
            <label for="{{blog.author}}">Author:</label>
            <select name="author" required id="id_author" class="form-control">
              <option value="">---------</option>
              <option value="1" selected>red</option> 
            </select>
          </div>

          <div class="form-group">
            <label for="id_post_count">Post count:</label>
            <input type="number" name="post_count" value="0" required id="id_post_count">
          </div>

          <div class="d-flex justify-content-end mt-3">
            <button type="submit" class="btn btn-primary mr-2">Update</button>
            <a href="{% url 'blog_list' %}" class="btn btn-secondary">Cancel</a>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

portfolio/templates/portfolio/combined_list.html
<!-- combined_list.html -->
{% extends 'portfolio/base.html' %}

{% block content %}
<div class="container mt-5 text-white">
    <div class="row">
        <div class="col-md-6 text-md-left text-center">
            <p class="mb-0">Welcome, {{ user.username }}</p>
        </div>
        <div class="col-md-6 text-md-right text-center">
            <!-- Logout button -->
            <form action="{% url 'user_logout' %}" method="post" class="mt-3">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger">Logout</button>
            </form>
        </div>
    </div>
    <hr>


    <h2 class="mt-5">Blogs</h2>
    <div class="mb-3">
        <a href="{% url 'add_blog' %}" class="btn btn-success mb-2">Add Blog</a>
    </div>
    <div class="row">
        {% for blog in blogs %}
        <div class="col-md-4">
            <div class="card mb-4">
                <div class="card-body">
                    <h5 class="card-title text-info">{{ blog.title }}</h5>
                    <a href="{% url 'update_blog' blog.slug %}" class="btn btn-warning">Edit</a>
                    <a href="{% url 'delete_blog' blog.slug %}" class="btn btn-danger">Delete</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <hr>


    <h2 class="mt-5">Projects</h2>
    <div class="mb-3">
        <a href="{% url 'add_project' %}" class="btn btn-success mb-2">Add Project</a>
    </div>
    <div class="row">
        {% for project in projects %}
        <div class="col-md-4">
            <div class="card mb-4 text-info">
                <div class="card-body">
                    <h5 class="card-title">{{ project.title }}</h5>
                    <a href="{% url 'update_project' project.pk %}" class="btn btn-warning">Edit</a>
                    <a href="{% url 'delete_project' project.pk %}" class="btn btn-danger">Delete</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <hr>


    <h2 class="mt-5">Photos</h2>
    <div class="mb-3">
        <a href="{% url 'add_photo' %}" class="btn btn-success mb-2">Add Photo</a>
    </div>
    <div class="row">
        {% for photo in photos %}
        <div class="col-md-4">
            <div class="card mb-4">
                <div class="card-body">
                    <h5 class="card-title text-info">Image URL: {{ photo.image_url }}</h5>
                    <a href="{% url 'update_photo' photo.pk %}" class="btn btn-warning">Edit</a>
                    <a href="{% url 'delete_photo' photo.pk %}" class="btn btn-danger">Delete</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}
<hr>

portfolio/templates/portfolio/photo_detail.html
{% extends 'portfolio/base.html' %}

{% block content %}
<div class="container mt-5" style="background-color: #f8f9fa; padding: 20px;">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-body text-center">
                    <!-- the image_url -->
                    <a href="{{ photo.image_url }}">
                        <img src="{{ photo.image_url }}" alt="{{ photo.caption }}" class="img-fluid mb-3" style="max-width: 100%;">
                    </a><br>
                    <!-- caption -->
                    <p>{{ photo.caption }}</p><br>   
                </div>
            </div>
        </div>
    </div>
</div><br><br>
{% endblock %}

portfolio/templates/portfolio/photo_update.html
<!-- photo_update.html -->
{% extends 'portfolio/base.html' %}

{% block content %}
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="card">
        <div class="card-body">
          <h1 class="text-center mb-4">Update Photo</h1>
          <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group">
              <label for="id_caption">Caption:</label>
              <input type="text" name="caption" id="id_caption" class="form-control">
            </div>
            <div class="form-group">
              
              {% if photo.image %}
                <p>Current Image: <img src="{{ photo.image.url }}" alt="{{ photo.caption }}" class="img-thumbnail" style="max-width: 200px;"></p>
              {% endif %}
            </div>
            <div class="form-group">
              <label for="id_image_url">Image URL:</label>
              {{ form.image_url.errors }}
              <input type="url" name="image_url" id="id_image_url" class="form-control">
            </div>
            <button type="submit" class="btn btn-primary btn-block">Save</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div><br><br>
{% endblock %}

portfolio/templates/portfolio/project_delete.html
{% extends 'portfolio/base.html' %}

{% block content %}
<div class="container" style="background-color: #343a40; padding: 20px; border-radius: 8px;">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="text-center text-white">
        <h1>Confirm Delete</h1>
        <p>Are you sure you want to delete the project "{{ project.title }}"?</p>
        <form method="post">
          {% csrf_token %}
          <div class="d-flex justify-content-center mt-3">
            <button type="submit" class="btn btn-danger mr-3">Yes, delete</button>
            <a href="{% url 'project_detail' project.pk %}" class="btn btn-secondary">Cancel</a>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

portfolio/templates/portfolio/project_detail.html
{% extends 'portfolio/base.html' %}

{% block content %}
<div class="container mt-5" style="background-color: #f8f9fa; padding: 20px;">
    <h2 class="text-center mb-4">Project Details</h2>

    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-body text-center">
                    <h3>{{ project.title }}</h3><br>
                    <p>{{ project.description }}</p><br>
                    <p><a href="{{project.project_link}}">{{project.project_link}}</a></p>
                </div>
            </div>
        </div>
    </div>
</div><br><br>
{% endblock %}

portfolio/templates/portfolio/project_list.html
{% extends 'portfolio/base.html' %}

{% block content %}
<div class="container mt-5 text-center">
    <div class="jumbotron">
        <h1>Projects</h1><br>
        <div class="container">
            <div class="row">
                {% for project in projects %}
                <div class="col-md-4 mb-4">
                    <div class="card h-100">
                        <div class="card-body">
                            <h5 class="card-title">{{ project.title }}</h5>
                            <a href="{% url 'project_detail' project.id %}" class="btn btn-primary">View Details</a>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
        <hr>
    </div>
</div><br>
{% endblock %}

portfolio/templates/portfolio/user_login.html
{% extends 'portfolio/base.html' %}

{% block content %}
<br><br><br>
<div class="container">
    <h1 class="text-info">Login</h1>
    <form method="POST" autocomplete="off" class="mt-4">
        {% csrf_token %}
        <div class="mb-3 text-white">
            <label for="id_username" class="form-label">Username:</label>
            <input type="text" name="username" class="form-control" id="id_username">
        </div>
        <div class="mb-3 text-white">
            <label for="id_password" class="form-label">Password:</label>
            <input type="password" name="password" class="form-control" id="id_password">
        </div>
        <button type="submit" class="btn btn-primary">Login</button>
    </form>
</div>
<br>
<br>
<br>
<hr>
{% endblock %}